# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e229dd8148976ba372835414668e7c271c5bd119195b9cd2c6768286fb992a7d40cc585d778ade4f5877e2d867accd12967e1b85f1af51930da27272dbd8580b

test:
  secret_key_base: 79aaeddb4f8f9fc33f5c36bff2d2dd35e2a7a6c3c5873944e10ccfcf907b7cf8fdfc37110d595472c53109d41afbd6af8e1f8ffc59b2794bd6c6d37e10e3c93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
